update action

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -30,25 +30,29 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: '3.10'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install build
+        pip install setuptools-scm
+
     - name: Build package
       run: python -m build --sdist --wheel --outdir dist/
-    - name: Upload results
+
+    # these will get purged at some point, but may as well upload in case its ever useful
+    - name: Upload results as artifact
       uses: actions/upload-artifact@v3
       with:
         name: test
         path: ./dist/
 
 
-    - name: fail action if not running on release
-      if: github.event_name != 'release'
-      run: |
-        echo 'you ran the release action on a non-release step, what are you doing????'
-        exit 1
-
+#    - name: fail action if not running on release
+#      if: github.event_name != 'release'
+#      run: |
+#        echo 'you ran the release action on a non-release step, what are you doing????'
+#        exit 1
 
     - name: Publish package
       # last resort condition
